/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/orders/{orderId}/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 주문 주소 변경 */
        put: operations["updateOrderAddress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회원 정보 조회 */
        get: operations["getMemberInfo"];
        /** 회원 정보 수정 */
        put: operations["updateMemberInfo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 주문 생성 */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원 로그인 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원 가입 */
        post: operations["join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주소 목록 조회 */
        get: operations["getAddressList"];
        put?: never;
        /** 주소 등록 */
        post: operations["submitAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주문 상세 조회 */
        get: operations["getOrderDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회원의 주문 내역 전체 조회 */
        get: operations["getMemberOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회원의 특정 주문 내역 상세 조회 */
        get: operations["getMemberOrderDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adm/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주문 목록 조회 */
        get: operations["getOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 주문 취소 */
        delete: operations["cancelOrder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 회원 탈퇴 */
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 회원 로그아웃 */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addresses/{addressId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 주소 삭제 */
        delete: operations["deleteAddress"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrderUpdateAddressReqBody: {
            newAddress: string;
        };
        RsDataVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: Record<string, never>;
        };
        MemberUpdateDto: {
            email: string;
            name: string;
            password: string;
        };
        MemberWithAuthDto: {
            /** Format: int64 */
            id: number;
            email: string;
            name: string;
            isAdmin: boolean;
        };
        RsDataMemberWithAuthDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MemberWithAuthDto"];
        };
        OrderCreateReqBody: {
            customerAddress: string;
            orderItems: components["schemas"]["OrderItemCreateReqBody"][];
        };
        OrderItemCreateReqBody: {
            /** Format: int64 */
            productId: number;
            /** Format: int32 */
            count: number;
        };
        /** @description 주문 정보 DTO */
        OrderDto: {
            /**
             * Format: int64
             * @description 주문 ID
             */
            id: number;
            /** @description 주문자 이메일 */
            customerEmail: string;
            /**
             * Format: date-time
             * @description 주문 날짜
             */
            createdDate: string;
            /**
             * @description 처리 상태
             * @example ORDERED
             * @enum {string}
             */
            state: "ORDERED" | "PAID" | "SHIPPING" | "COMPLETED" | "CANCELED" | "ORDERED" | "PAID" | "SHIPPING" | "COMPLETED" | "CANCELED";
            /** @description 주문 주소 */
            customerAddress: string;
            /** @description 주문 상세 목록 */
            orderItems: components["schemas"]["OrderItemDto"][];
        };
        /** @description 상세 주문 정보 DTO */
        OrderItemDto: {
            /**
             * Format: int64
             * @description 주문 아이템 ID
             */
            id: number;
            /**
             * Format: int64
             * @description 주문 ID
             */
            orderId: number;
            /**
             * Format: int64
             * @description 상품 ID
             */
            productId: number;
            /**
             * Format: int32
             * @description 수량
             */
            count: number;
            /**
             * Format: int32
             * @description 낱개 가격
             */
            price: number;
        };
        RsDataOrderDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["OrderDto"];
        };
        MemberLoginReqBody: {
            email: string;
            password: string;
        };
        MemberLoginResBody: {
            member?: components["schemas"]["MemberWithAuthDto"];
            apiKey?: string;
            accessToken?: string;
        };
        RsDataMemberLoginResBody: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MemberLoginResBody"];
        };
        MemberJoinReqBody: {
            email: string;
            password: string;
            name: string;
        };
        MemberDto: {
            /** Format: int64 */
            id: number;
            email: string;
            name: string;
        };
        RsDataMemberDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MemberDto"];
        };
        AddressSubmitReqBody: {
            content: string;
        };
        AddressSubmitResBody: {
            /** Format: int64 */
            id?: number;
            content?: string;
            member?: components["schemas"]["MemberDto"];
        };
        RsDataAddressSubmitResBody: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AddressSubmitResBody"];
        };
        /** @description 주문 상세 정보 DTO */
        OrderDtoWithSpecific: {
            /**
             * Format: int64
             * @description 주문 ID
             */
            id?: number;
            /** @description 주문자 이메일 */
            customerEmail?: string;
            /** @description 주문 배송 주소 */
            customerAddress?: string;
            /**
             * @description 주문 상태 코드
             * @example ORDERED
             * @enum {string}
             */
            state?: "ORDERED" | "PAID" | "SHIPPING" | "COMPLETED" | "CANCELED";
            /**
             * Format: date-time
             * @description 주문 생성일
             */
            createdDate?: string;
            /** @description 주문에 포함된 상품 목록 */
            orderItems?: components["schemas"]["OrderItemDto"][];
        };
        RsDataOrderDtoWithSpecific: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["OrderDtoWithSpecific"];
        };
        "RsDataUserOrderResponseBody[]": {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["UserOrderResponseBody"][];
        };
        UserOrderItemResponseDto: {
            productName?: string;
            /** Format: int64 */
            productId?: number;
            /** Format: int32 */
            count?: number;
            /** Format: int32 */
            price?: number;
        };
        UserOrderResponseBody: {
            /** Format: int64 */
            orderId?: number;
            orderDate?: string;
            status?: string;
            customerAddress?: string;
            orderItems?: components["schemas"]["UserOrderItemResponseDto"][];
        };
        RsDataUserOrderDetailResponseBody: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["UserOrderDetailResponseBody"];
        };
        UserOrderDetailResponseBody: {
            /** Format: int64 */
            orderId?: number;
            orderDate?: string;
            status?: string;
            customerAddress?: string;
            orderItems?: components["schemas"]["UserOrderItemDetailResponseDto"][];
        };
        UserOrderItemDetailResponseDto: {
            productName?: string;
            /** Format: int64 */
            productId?: number;
            productImageUrl?: string;
            productCategory?: string;
            /** Format: int32 */
            count?: number;
            /** Format: int32 */
            price?: number;
        };
        RsDataListOrderDto: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["OrderDto"][];
        };
        AddressListResBody: {
            /** Format: int64 */
            id?: number;
            content?: string;
            isDefault?: boolean;
        };
        "RsDataAddressListResBody[]": {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AddressListResBody"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateOrderAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderUpdateAddressReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getMemberInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMemberWithAuthDto"];
                };
            };
        };
    };
    updateMemberInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMemberWithAuthDto"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataOrderDto"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberLoginReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMemberLoginResBody"];
                };
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberJoinReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMemberDto"];
                };
            };
        };
    };
    getAddressList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataAddressListResBody[]"];
                };
            };
        };
    };
    submitAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressSubmitReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataAddressSubmitResBody"];
                };
            };
        };
    };
    getOrderDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataOrderDtoWithSpecific"];
                };
            };
        };
    };
    getMemberOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataUserOrderResponseBody[]"];
                };
            };
        };
    };
    getMemberOrderDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataUserOrderDetailResponseBody"];
                };
            };
        };
    };
    getOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListOrderDto"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    deleteAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
}
